/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{jsx,js}"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "secondary-container": "#03b5d3",
        "surface-container-lowest": "#0e0d16",
        "on-error": "#690005",
        "surface-tint": "#c3c0ff",
        "secondary": "#4cd7f6",
        "on-primary-fixed-variant": "#3323cc",
        "surface-container-high": "#2a2933",
        "on-primary-container": "#dad7ff",
        "primary-container": "#4f46e5",
        "on-tertiary-fixed-variant": "#7b2f00",
        "tertiary-fixed": "#ffdbcc",
        "primary-fixed": "#e2dfff",
        "secondary-fixed-dim": "#4cd7f6",
        "on-tertiary-container": "#ffd2be",
        "on-secondary-container": "#00424e",
        "inverse-surface": "#e4e1ee",
        "background": "#13121b",
        "on-background": "#e4e1ee",
        "tertiary-container": "#a44100",
        "on-secondary-fixed-variant": "#004e5c",
        "on-surface": "#e4e1ee",
        "primary-fixed-dim": "#c3c0ff",
        "surface-dim": "#13121b",
        "on-primary-fixed": "#0f0069",
        "surface-container-low": "#1b1b24",
        "surface": "#13121b",
        "on-tertiary-fixed": "#351000",
        "surface-container-highest": "#35343e",
        "on-surface-variant": "#c7c4d8",
        "on-tertiary": "#571f00",
        "on-secondary-fixed": "#001f26",
        "surface-bright": "#393842",
        "surface-variant": "#35343e",
        "on-secondary": "#003640",
        "on-primary": "#1d00a5",
        "error": "#ffb4ab",
        "primary": "#c3c0ff",
        "tertiary-fixed-dim": "#ffb695",
        "outline-variant": "#464555",
        "inverse-on-surface": "#302f39",
        "outline": "#918fa1",
        "secondary-fixed": "#acedff",
        "inverse-primary": "#4d44e3",
        "surface-container": "#1f1f28",
        "error-container": "#93000a",
        "tertiary": "#ffb695",
        "on-error-container": "#ffdad6",
        "obsidian": "#0A0A0F",
        "card-bg": "#11111A",
        "panel-bg": "#1A1A24",
      },
      backgroundColor: {
        'paper': 'rgb(var(--paper) / <alpha-value>)',
        'surface': 'rgb(var(--surface) / <alpha-value>)',
        'panel': 'rgb(var(--panel) / <alpha-value>)',
      },
      textColor: {
        'ink': 'rgb(var(--ink) / <alpha-value>)',
        'muted': 'rgb(var(--muted) / <alpha-value>)',
        'faint': 'rgb(var(--faint) / <alpha-value>)',
      },
      borderColor: {
        'line': 'rgb(var(--line) / <alpha-value>)',
      },
      borderRadius: {
        'xs': 'var(--radius-xs)',
        'sm': 'var(--radius-sm)',
        'md': 'var(--radius-md)',
        'lg': 'var(--radius-lg)',
        'xl': 'var(--radius-lg)',
        '2xl': '24px',
        'full': 'var(--radius-full)',
      },
      spacing: {
        gutter: "24px",
        "margin-mobile": "16px",
        unit: "4px",
        "margin-desktop": "64px",
        "max-width": "1440px",
      },
      fontFamily: {
        "body-lg": ["Geist", "sans-serif"],
        code: ["JetBrains Mono", "monospace"],
        "label-sm": ["JetBrains Mono", "monospace"],
        "headline-lg": ["Geist", "sans-serif"],
        "headline-md": ["Geist", "sans-serif"],
        "headline-lg-mobile": ["Geist", "sans-serif"],
        "body-md": ["Geist", "sans-serif"],
      },
      fontSize: {
        "body-lg": [
          "18px",
          {
            lineHeight: "28px",
            letterSpacing: "0.01em",
            fontWeight: "400",
          },
        ],
        code: [
          "14px",
          {
            lineHeight: "20px",
            fontWeight: "400",
          },
        ],
        "label-sm": [
          "12px",
          {
            lineHeight: "16px",
            letterSpacing: "0.08em",
            fontWeight: "500",
          },
        ],
        "headline-lg": [
          "48px",
          {
            lineHeight: "56px",
            letterSpacing: "-0.02em",
            fontWeight: "700",
          },
        ],
        "headline-md": [
          "24px",
          {
            lineHeight: "32px",
            letterSpacing: "-0.01em",
            fontWeight: "600",
          },
        ],
        "headline-lg-mobile": [
          "32px",
          {
            lineHeight: "40px",
            letterSpacing: "-0.01em",
            fontWeight: "700",
          },
        ],
        "body-md": [
          "16px",
          {
            lineHeight: "24px",
            letterSpacing: "0.01em",
            fontWeight: "400",
          },
        ],
      },
    },
  },
  plugins: [],
}
